title: "Chip — Reverse Engineering & CTFs"
description: "Reverse engineering, CTF write-ups, tools, and research by Chip."
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  writeups:
    output: true
    permalink: /writeups/:name/
