title: "Chip Biscuit"
description: "Write-ups, reverse engineering, and cybersecurity research."
theme: null
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "writeups"
      type: "pages"
    values:
      layout: default

# Keep the _includes and _layouts folders in the build
include:
  - _includes
  - _layouts
  - assets

url: "https://chip-biscuit.github.io"

social_title: 'Chip — “What I cannot create, I do not understand.”'
social_desc:  '“What I cannot create, I do not understand.”'
social_image: '/assets/images/social-card-v4.png'  # keep this path
