title: "Chip Biscuit"
description: "Write-ups, reverse engineering, and cybersecurity research."
theme: null
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "writeups"
      type: "pages"
    values:
      layout: default

# Keep the _includes and _layouts folders in the build
include:
  - _includes
  - _layouts
  - assets
